const emojipedia = [
  { id: 1, emoji: "😀", name: "Grinning Face", meaning: "A classic, happy grin." },
  { id: 2, emoji: "😍", name: "Heart Eyes", meaning: "In love or extremely happy." },
  { id: 3, emoji: "🥺", name: "Pleading Face", meaning: "Expresses a pleading or begging emotion." },
  { id: 4, emoji: "🤔", name: "Thinking Face", meaning: "Deep in thought or questioning something." },
  { id: 5, emoji: "🤩", name: "Star-Struck", meaning: "Impressed or amazed by something." },
  { id: 6, emoji: "😎", name: "Cool Face", meaning: "Feeling cool, confident, or relaxed." },
  { id: 7, emoji: "🥳", name: "Party Face", meaning: "Celebrating good times and having fun." },
  { id: 8, emoji: "😇", name: "Smiling Face with Halo", meaning: "Innocent, angelic, or good-natured." },
  { id: 9, emoji: "😴", name: "Sleeping Face", meaning: "Tired or ready for bed." },
  { id: 10, emoji: "🤑", name: "Money-Mouth Face", meaning: "Feeling rich or successful." },
  { id: 11, emoji: "😷", name: "Face with Medical Mask", meaning: "Wearing a mask for health or pollution reasons." },
  { id: 12, emoji: "🤯", name: "Face with Exploding Head", meaning: "Mind-blown or overwhelmed with amazement." },
  { id: 13, emoji: "🤢", name: "Nauseated Face", meaning: "Feeling sick or disgusted." },
  { id: 14, emoji: "🤭", name: "Face with Hand Over Mouth", meaning: "Surprised, shocked, or trying to be secretive." },
  { id: 15, emoji: "😒", name: "Unamused Face", meaning: "Not amused, indifferent, or unimpressed." },
  { id: 16, emoji: "🤐", name: "Zipper-Mouth Face", meaning: "Keeping a secret or speechless." },
  { id: 17, emoji: "😲", name: "Astonished Face", meaning: "Extremely surprised or shocked." },
  { id: 18, emoji: "😔", name: "Pensive Face", meaning: "Thoughtful, sad, or reflective." },
  { id: 19, emoji: "🥰", name: "Smiling Face with Hearts", meaning: "Overwhelmed with love or affection." },
  { id: 20, emoji: "🤪", name: "Crazy Face", meaning: "Excited, silly, or out of control." },
  { id: 21, emoji: "🤠", name: "Cowboy Hat Face", meaning: "Yeehaw! Howdy, partner!" },
  { id: 22, emoji: "🤓", name: "Nerd Face", meaning: "Intellectual, studious, or socially awkward." },
  { id: 23, emoji: "😈", name: "Smiling Face with Horns", meaning: "Playfully mischievous or devilish." },
  { id: 24, emoji: "🤖", name: "Robot Face", meaning: "Mechanical or robotic in nature." },
  { id: 25, emoji: "👽", name: "Alien", meaning: "Extraterrestrial being from outer space." },
  { id: 26, emoji: "🤖", name: "Robot Face", meaning: "Mechanical or robotic in nature." },
  { id: 27, emoji: "👾", name: "Alien Monster", meaning: "Friendly or silly extraterrestrial creature." },
  { id: 28, emoji: "🤖", name: "Robot Face", meaning: "Mechanical or robotic in nature." },
  { id: 29, emoji: "🤖", name: "Robot Face", meaning: "Mechanical or robotic in nature." },
  { id: 30, emoji: "🎃", name: "Jack-O-Lantern", meaning: "Halloween, spooky, or festive." },
  { id: 31, emoji: "👻", name: "Ghost", meaning: "Spooky or playful ghost." },
  { id: 32, emoji: "🍔", name: "Hamburger", meaning: "Delicious fast food item." },
  { id: 33, emoji: "🍕", name: "Pizza", meaning: "Classic Italian dish." },
  { id: 34, emoji: "🌮", name: "Taco", meaning: "Mexican cuisine, a tasty treat." },
  { id: 35, emoji: "🍦", name: "Ice Cream", meaning: "Sweet and cold dessert." },
  { id: 36, emoji: "🍩", name: "Doughnut", meaning: "Fried pastry, often sweet and ring-shaped." },
  { id: 37, emoji: "🍿", name: "Popcorn", meaning: "Snack for movies or entertainment." },
  { id: 38, emoji: "🍭", name: "Lollipop", meaning: "Colorful candy on a stick." },
  { id: 39, emoji: "🍓", name: "Strawberry", meaning: "Sweet and juicy red fruit." },
  { id: 40, emoji: "🍌", name: "Banana", meaning: "Yellow fruit, a good source of potassium." },
  { id: 41, emoji: "🍎", name: "Red Apple", meaning: "Classic fruit, often associated with teachers." },
  { id: 42, emoji: "🍇", name: "Grapes", meaning: "Bunch of grapes, a healthy snack." },
  { id: 43, emoji: "🥭", name: "Mango", meaning: "Exotic and juicy tropical fruit." },
  { id: 44, emoji: "🍉", name: "Watermelon", meaning: "Sweet and refreshing summer fruit." },
  { id: 45, emoji: "🍒", name: "Cherries", meaning: "Two red cherries with stems." },
  { id: 46, emoji: "🥑", name: "Avocado", meaning: "Green fruit with a large pit, often used in guacamole." },
  { id: 47, emoji: "🌽", name: "Ear of Corn", meaning: "Yellow corn on the cob." },
  { id: 48, emoji: "🍄", name: "Mushroom", meaning: "Edible fungi, often used in cooking." },
  { id: 49, emoji: "🍔", name: "Hamburger", meaning: "Delicious fast food item." },
  { id: 50, emoji: "🍕", name: "Pizza", meaning: "Classic Italian dish." },
  { id: 51, emoji: "🌮", name: "Taco", meaning: "Mexican cuisine, a tasty treat." },
  { id: 52, emoji: "🍦", name: "Ice Cream", meaning: "Sweet and cold dessert." },
  { id: 53, emoji: "🍩", name: "Doughnut", meaning: "Fried pastry, often sweet and ring-shaped." },
  { id: 54, emoji: "🍿", name: "Popcorn", meaning: "Snack for movies or entertainment." },
  { id: 55, emoji: "🍭", name: "Lollipop", meaning: "Colorful candy on a stick." },
  { id: 56, emoji: "🍓", name: "Strawberry", meaning: "Sweet and juicy red fruit." },
  { id: 57, emoji: "🍌", name: "Banana", meaning: "Yellow fruit, a good source of potassium." },
  { id: 58, emoji: "🍎", name: "Red Apple", meaning: "Classic fruit, often associated with teachers." },
  { id: 59, emoji: "🍇", name: "Grapes", meaning: "Bunch of grapes, a healthy snack." },
  { id: 60, emoji: "🥭", name: "Mango", meaning: "Exotic and juicy tropical fruit." },
  { id: 61, emoji: "🍉", name: "Watermelon", meaning: "Sweet and refreshing summer fruit." },
  { id: 62, emoji: "🍒", name: "Cherries", meaning: "Two red cherries with stems." },
  { id: 63, emoji: "🥑", name: "Avocado", meaning: "Green fruit with a large pit, often used in guacamole." },
  { id: 64, emoji: "🌽", name: "Ear of Corn", meaning: "Yellow corn on the cob." },
  { id: 65, emoji: "🍄", name: "Mushroom", meaning: "Edible fungi, often used in cooking." },
  { id: 66, emoji: "🍔", name: "Hamburger", meaning: "Delicious fast food item." },
  { id: 67, emoji: "🍕", name: "Pizza", meaning: "Classic Italian dish." },
  { id: 68, emoji: "🌮", name: "Taco", meaning: "Mexican cuisine, a tasty treat." },
  { id: 69, emoji: "🍦", name: "Ice Cream", meaning: "Sweet and cold dessert." },
  { id: 70, emoji: "🍩", name: "Doughnut", meaning: "Fried pastry, often sweet and ring-shaped." },
  { id: 71, emoji: "🍿", name: "Popcorn", meaning: "Snack for movies or entertainment." },
  { id: 72, emoji: "🍭", name: "Lollipop", meaning: "Colorful candy on a stick." },
  { id: 73, emoji: "🍓", name: "Strawberry", meaning: "Sweet and juicy red fruit." },
  { id: 74, emoji: "🍌", name: "Banana", meaning: "Yellow fruit, a good source of potassium." },
  { id: 75, emoji: "🍎", name: "Red Apple", meaning: "Classic fruit, often associated with teachers." },
  { id: 76, emoji: "🍇", name: "Grapes", meaning: "Bunch of grapes, a healthy snack." },
  { id: 77, emoji: "🥭", name: "Mango", meaning: "Exotic and juicy tropical fruit." },
  { id: 78, emoji: "🍉", name: "Watermelon", meaning: "Sweet and refreshing summer fruit." },
  { id: 79, emoji: "🍒", name: "Cherries", meaning: "Two red cherries with stems." },
  { id: 80, emoji: "🥑", name: "Avocado", meaning: "Green fruit with a large pit, often used in guacamole." },
  { id: 81, emoji: "🌽", name: "Ear of Corn", meaning: "Yellow corn on the cob." },
  { id: 82, emoji: "🍄", name: "Mushroom", meaning: "Edible fungi, often used in cooking." },
  { id: 83, emoji: "🍔", name: "Hamburger", meaning: "Delicious fast food item." },
  { id: 84, emoji: "🍕", name: "Pizza", meaning: "Classic Italian dish." },
  { id: 85, emoji: "🌮", name: "Taco", meaning: "Mexican cuisine, a tasty treat." },
  { id: 86, emoji: "🍦", name: "Ice Cream", meaning: "Sweet and cold dessert." },
  { id: 87, emoji: "🍩", name: "Doughnut", meaning: "Fried pastry, often sweet and ring-shaped." },
  { id: 88, emoji: "🍿", name: "Popcorn", meaning: "Snack for movies or entertainment." },
  { id: 89, emoji: "🍭", name: "Lollipop", meaning: "Colorful candy on a stick." },
  { id: 90, emoji: "🍓", name: "Strawberry", meaning: "Sweet and juicy red fruit." },
  { id: 91, emoji: "🍌", name: "Banana", meaning: "Yellow fruit, a good source of potassium." },
  { id: 92, emoji: "🍎", name: "Red Apple", meaning: "Classic fruit, often associated with teachers." },
  { id: 93, emoji: "🍇", name: "Grapes", meaning: "Bunch of grapes, a healthy snack." },
  { id: 94, emoji: "🥭", name: "Mango", meaning: "Exotic and juicy tropical fruit." },
];

export default emojipedia;